# Generated by Django 5.2.4 on 2025-07-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('username', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('comment_date', models.DateTimeField()),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('parent_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('chat_id', models.CharField(max_length=255)),
            ],
        ),
    ]
